version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  presto:
    image: prestodb/presto:latest
    container_name: presto
    ports:
      - "8443:8443"  # Thay đổi cổng nếu cần
      - "8080:8080"
    volumes:
      - F:/code/java/day/testimportexcel/config.properties:/etc/presto/config.properties
      - F:/code/java/day/testimportexcel/mysql.properties:/etc/presto/catalog/mysql.properties
    environment:
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/etc/presto/ca.crt
      - JAVA_OPTS=-Djavax.net.ssl.trustStorePassword=123456  # Nếu cần
      - JAVA_OPTS=-Djavax.net.ssl.keyStore=/etc/presto/server.p12
      - JAVA_OPTS=-Djavax.net.ssl.keyStorePassword=123456  # Thay đổi mật khẩu tương ứng
      - JAVA_OPTS=-Djavax.net.ssl.keyStoreType=PKCS12
    command:
      presto-server --config /etc/presto/config.properties
    depends_on:
      - mariadb
volumes:
  db_data:
